import type { RacquetSpec } from "./types";

const OBSERVED_AT = "2026-06-15";

export const RACQUET_SPECS: RacquetSpec[] = [
  {
    slug: "tecnifibre-carboflex-125-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 125 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Dynamix VP",
    sources: [
      {
        type: "official",
        name: "Tecnifibre",
        url: "https://www.tecnifibre.com/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
        notes: "Manufacturer family page and product spec listings.",
      },
    ],
  },
  {
    slug: "tecnifibre-carboflex-130-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 130 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 130,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    sources: [
      {
        type: "official",
        name: "Tecnifibre",
        url: "https://www.tecnifibre.com/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "dunlop-sonic-core-revelation-pro",
    brand: "Dunlop",
    model: "Sonic Core Revelation Pro",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 128,
    balanceMm: 360,
    headSizeCm2: 490,
    lengthMm: 686,
    stringPattern: "14x19",
    recommendedTensionLb: [20, 30],
    sources: [
      {
        type: "official",
        name: "Dunlop Sports",
        url: "https://dunlopsports.com/products/squash/rackets/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "dunlop-sonic-core-elite-135",
    brand: "Dunlop",
    model: "Sonic Core Elite 135",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 135,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [
      {
        type: "official",
        name: "Dunlop Sports",
        url: "https://dunlopsports.com/products/squash/rackets/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "head-speed-120-slimbody",
    brand: "HEAD",
    model: "Speed 120 Slimbody",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "HEAD",
        url: "https://www.head.com/en_US/squash/squash-racquets.html",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "head-radical-135-slimbody",
    brand: "HEAD",
    model: "Radical 135 Slimbody",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 135,
    balanceMm: 370,
    headSizeCm2: 475,
    lengthMm: 685,
    stringPattern: "14x16",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "HEAD",
        url: "https://www.head.com/en_US/squash/squash-racquets.html",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "unsquashable-y-tec-125",
    brand: "UNSQUASHABLE",
    model: "Y-TEC 125",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "UNSQUASHABLE",
        url: "https://unsquashable.com/collections/squash-rackets",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "karakal-raw-120",
    brand: "Karakal",
    model: "Raw 120",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "Karakal",
        url: "https://www.karakal.com/collections/squash-rackets",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
];
