import type { CatalogSource, RacquetSpec } from "./types";

const OBSERVED_AT = "2026-06-15";

const officialSource = (name: string, url: string, notes?: string): CatalogSource => ({
  type: "official",
  name,
  url,
  observedAt: OBSERVED_AT,
  confidence: "medium",
  ...(notes ? { notes } : {}),
});

const retailerSource = (name: string, url: string, notes?: string): CatalogSource => ({
  type: "retailer",
  name,
  url,
  observedAt: OBSERVED_AT,
  confidence: "medium",
  ...(notes ? { notes } : {}),
});

export const RACQUET_SPECS: RacquetSpec[] = [
  {
    slug: "tecnifibre-carboflex-125-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 125 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Dynamix VP",
    sources: [
      {
        type: "official",
        name: "Tecnifibre",
        url: "https://www.tecnifibre.com/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
        notes: "Manufacturer family page and product spec listings.",
      },
    ],
  },
  {
    slug: "tecnifibre-carboflex-130-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 130 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 130,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    sources: [
      {
        type: "official",
        name: "Tecnifibre",
        url: "https://www.tecnifibre.com/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "dunlop-sonic-core-revelation-pro",
    brand: "Dunlop",
    model: "Sonic Core Revelation Pro",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 128,
    balanceMm: 360,
    headSizeCm2: 490,
    lengthMm: 686,
    stringPattern: "14x19",
    recommendedTensionLb: [20, 30],
    sources: [
      {
        type: "official",
        name: "Dunlop Sports",
        url: "https://dunlopsports.com/products/squash/rackets/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "dunlop-sonic-core-elite-135",
    brand: "Dunlop",
    model: "Sonic Core Elite 135",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 135,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [
      {
        type: "official",
        name: "Dunlop Sports",
        url: "https://dunlopsports.com/products/squash/rackets/",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "head-speed-120-slimbody",
    brand: "HEAD",
    model: "Speed 120 Slimbody",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "HEAD",
        url: "https://www.head.com/en_US/squash/squash-racquets.html",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "head-radical-135-slimbody",
    brand: "HEAD",
    model: "Radical 135 Slimbody",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 135,
    balanceMm: 370,
    headSizeCm2: 475,
    lengthMm: 685,
    stringPattern: "14x16",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "HEAD",
        url: "https://www.head.com/en_US/squash/squash-racquets.html",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "unsquashable-y-tec-125",
    brand: "UNSQUASHABLE",
    model: "Y-TEC 125",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "UNSQUASHABLE",
        url: "https://unsquashable.com/collections/squash-rackets",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "karakal-raw-120",
    brand: "Karakal",
    model: "Raw 120",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [
      {
        type: "official",
        name: "Karakal",
        url: "https://www.karakal.com/collections/squash-rackets",
        observedAt: OBSERVED_AT,
        confidence: "medium",
      },
    ],
  },
  {
    slug: "tecnifibre-carboflex-120-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 120 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Dynamix VP",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-carboflex-125-ns-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 125 NS X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Dynamix VP",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-carboflex-135-x-top-v2",
    brand: "Tecnifibre",
    model: "Carboflex 135 X-Top V2",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 355,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Dynamix VP",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-slash-120-control",
    brand: "Tecnifibre",
    model: "Slash 120 Control",
    modelYear: 2025,
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 461,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre 305 Green",
    sources: [
      officialSource(
        "Tecnifibre",
        "https://www.mytecnifibre.com/Slash-120-Control",
        "Manufacturer listing: 120 g, 350 mm balance, 461 cm2 head, 14x18 pattern.",
      ),
    ],
  },
  {
    slug: "tecnifibre-slash-120-power",
    brand: "Tecnifibre",
    model: "Slash 120 Power",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 485,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre 305 Green",
    sources: [
      officialSource(
        "Tecnifibre",
        "https://www.mytecnifibre.com/Slash-120-Power",
        "Manufacturer listing: 120 g, 350 mm balance, 485 cm2 head, 14x18 pattern.",
      ),
    ],
  },
  {
    slug: "tecnifibre-slash-130-power",
    brand: "Tecnifibre",
    model: "Slash 130 Power",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 130,
    balanceMm: 355,
    headSizeCm2: 485,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre 305 Green",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-slash-135-power",
    brand: "Tecnifibre",
    model: "Slash 135 Power",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 355,
    headSizeCm2: 485,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre 305 Green",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-slash-team",
    brand: "Tecnifibre",
    model: "Slash Team",
    modelYear: 2025,
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 150,
    balanceMm: 360,
    headSizeCm2: 485,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    factoryString: "Tecnifibre Synthetic Gut",
    sources: [officialSource("Tecnifibre", "https://b2b.tecnifibre.com/en/squash/squash-rackets/")],
  },
  {
    slug: "tecnifibre-suprem-125-curv",
    brand: "Tecnifibre",
    model: "Suprem 125 CurV",
    status: "recent",
    frameFamily: "traditional",
    advertisedWeightG: 125,
    balanceMm: 350,
    headSizeCm2: 470,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    sources: [retailerSource("SquashGalaxy", "https://www.squashgalaxy.com/tecnifibre-squash-racquets.html")],
  },
  {
    slug: "tecnifibre-dynergy-apx-130",
    brand: "Tecnifibre",
    model: "Dynergy APX 130",
    status: "recent",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 490,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [23, 29],
    sources: [retailerSource("SquashGalaxy", "https://www.squashgalaxy.com/tecnifibre-squash-racquets.html")],
  },
  {
    slug: "head-speed-110",
    brand: "HEAD",
    model: "Speed 110",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 110,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-speed-120",
    brand: "HEAD",
    model: "Speed 120",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-speed-135",
    brand: "HEAD",
    model: "Speed 135",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-extreme-120",
    brand: "HEAD",
    model: "Extreme 120",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 120,
    balanceMm: 375,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-extreme-135",
    brand: "HEAD",
    model: "Extreme 135",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 375,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-radical-120-slimbody",
    brand: "HEAD",
    model: "Radical 120 Slimbody",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 120,
    balanceMm: 370,
    headSizeCm2: 475,
    lengthMm: 685,
    stringPattern: "14x16",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-radical-135",
    brand: "HEAD",
    model: "Radical 135",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 135,
    balanceMm: 365,
    headSizeCm2: 475,
    lengthMm: 685,
    stringPattern: "14x16",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-ig-challenge-135",
    brand: "HEAD",
    model: "IG Challenge 135",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 135,
    balanceMm: 335,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "head-graphene-360-speed-125",
    brand: "HEAD",
    model: "Graphene 360+ Speed 125",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 685,
    stringPattern: "12x17",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("HEAD", "https://www.head.com/en_US/squash/squash-racquets.html")],
  },
  {
    slug: "dunlop-sonic-core-revelation-125",
    brand: "Dunlop",
    model: "Sonic Core Revelation 125",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 360,
    headSizeCm2: 490,
    lengthMm: 686,
    stringPattern: "14x19",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-sonic-core-revelation-pro-lite",
    brand: "Dunlop",
    model: "Sonic Core Revelation Pro Lite",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 360,
    headSizeCm2: 490,
    lengthMm: 686,
    stringPattern: "14x19",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-sonic-core-evolution-120",
    brand: "Dunlop",
    model: "Sonic Core Evolution 120",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 120,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-sonic-core-evolution-130",
    brand: "Dunlop",
    model: "Sonic Core Evolution 130",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-sonic-core-pro-130",
    brand: "Dunlop",
    model: "Sonic Core Pro 130",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 470,
    lengthMm: 686,
    stringPattern: "16x19",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-sonic-core-ultimate-132",
    brand: "Dunlop",
    model: "Sonic Core Ultimate 132",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 132,
    balanceMm: 365,
    headSizeCm2: 470,
    lengthMm: 686,
    stringPattern: "16x19",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-tristorm-pro-125",
    brand: "Dunlop",
    model: "Tristorm Pro 125",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 355,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-tristorm-elite-145",
    brand: "Dunlop",
    model: "Tristorm Elite 145",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 145,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "dunlop-blaze-pro-130",
    brand: "Dunlop",
    model: "Blaze Pro 130",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [20, 30],
    sources: [officialSource("Dunlop Sports", "https://dunlopsports.com/products/squash/rackets/")],
  },
  {
    slug: "unsquashable-y-tec-pro-125",
    brand: "UNSQUASHABLE",
    model: "Y-TEC PRO 125",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("UNSQUASHABLE", "https://unsquashable.com/collections/squash-rackets")],
  },
  {
    slug: "unsquashable-y-tec-135",
    brand: "UNSQUASHABLE",
    model: "Y-TEC 135",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("UNSQUASHABLE", "https://unsquashable.com/collections/squash-rackets")],
  },
  {
    slug: "unsquashable-aero-tec-125",
    brand: "UNSQUASHABLE",
    model: "AERO-TEC 125",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 125,
    balanceMm: 365,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("UNSQUASHABLE", "https://unsquashable.com/collections/squash-rackets")],
  },
  {
    slug: "unsquashable-james-willstrop-autograph",
    brand: "UNSQUASHABLE",
    model: "James Willstrop Autograph",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 135,
    balanceMm: 360,
    headSizeCm2: 470,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("UNSQUASHABLE", "https://unsquashable.com/collections/squash-rackets")],
  },
  {
    slug: "unsquashable-jahangir-khan-555",
    brand: "UNSQUASHABLE",
    model: "Jahangir Khan 555",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 150,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("UNSQUASHABLE", "https://unsquashable.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-raw-pro-2-0",
    brand: "Karakal",
    model: "Raw Pro 2.0",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 120,
    balanceMm: 350,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-raw-110",
    brand: "Karakal",
    model: "Raw 110",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 110,
    balanceMm: 355,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-raw-130",
    brand: "Karakal",
    model: "Raw 130",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-s-pro-elite",
    brand: "Karakal",
    model: "S Pro Elite",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 125,
    balanceMm: 355,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-core-pro",
    brand: "Karakal",
    model: "Core Pro",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 125,
    balanceMm: 360,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "karakal-tec-pro-elite",
    brand: "Karakal",
    model: "Tec Pro Elite",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 125,
    balanceMm: 355,
    headSizeCm2: 480,
    lengthMm: 685,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 28],
    sources: [officialSource("Karakal", "https://www.karakal.com/collections/squash-rackets")],
  },
  {
    slug: "wilson-hyper-hammer-120",
    brand: "Wilson",
    model: "Hyper Hammer 120",
    status: "recent",
    frameFamily: "traditional",
    advertisedWeightG: 120,
    balanceMm: 375,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "wilson-hammer-110",
    brand: "Wilson",
    model: "Hammer 110",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 110,
    balanceMm: 375,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "wilson-blade-500",
    brand: "Wilson",
    model: "Blade 500",
    status: "recent",
    frameFamily: "traditional",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "wilson-blade-team",
    brand: "Wilson",
    model: "Blade Team",
    status: "recent",
    frameFamily: "traditional",
    advertisedWeightG: 150,
    balanceMm: 350,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "wilson-tempest-pro",
    brand: "Wilson",
    model: "Tempest Pro",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 135,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "wilson-tempest-lite",
    brand: "Wilson",
    model: "Tempest Lite",
    status: "recent",
    frameFamily: "teardrop",
    advertisedWeightG: 134,
    balanceMm: 370,
    headSizeCm2: 500,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Wilson", "https://www.wilson.com/en-us/c/squash-rackets")],
  },
  {
    slug: "prince-pro-airstick-550",
    brand: "Prince",
    model: "Pro Airstick 550",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 480,
    lengthMm: 686,
    stringPattern: "16x17",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Prince", "https://www.princesports.com/collections/squash-racquets")],
  },
  {
    slug: "prince-pro-beast-750",
    brand: "Prince",
    model: "Pro Beast 750",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 365,
    headSizeCm2: 480,
    lengthMm: 686,
    stringPattern: "16x17",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Prince", "https://www.princesports.com/collections/squash-racquets")],
  },
  {
    slug: "prince-venom-pro-950",
    brand: "Prince",
    model: "Venom Pro 950",
    status: "current",
    frameFamily: "teardrop",
    advertisedWeightG: 125,
    balanceMm: 370,
    headSizeCm2: 485,
    lengthMm: 686,
    stringPattern: "16x17",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Prince", "https://www.princesports.com/collections/squash-racquets")],
  },
  {
    slug: "prince-vortex-pro-650",
    brand: "Prince",
    model: "Vortex Pro 650",
    status: "current",
    frameFamily: "hybrid",
    advertisedWeightG: 130,
    balanceMm: 360,
    headSizeCm2: 475,
    lengthMm: 686,
    stringPattern: "16x17",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Prince", "https://www.princesports.com/collections/squash-racquets")],
  },
  {
    slug: "harrow-vapor",
    brand: "Harrow",
    model: "Vapor",
    status: "current",
    frameFamily: "traditional",
    advertisedWeightG: 140,
    balanceMm: 370,
    headSizeCm2: 470,
    lengthMm: 686,
    stringPattern: "14x18",
    recommendedTensionLb: [24, 30],
    sources: [officialSource("Harrow", "https://www.harrowsports.com/collections/squash-racquets")],
  },
];
